Make hls the unique language server variant
haskell/vscode-haskell pull request #362
Opened 2021-03-11 23:04 UTC by jneira

* I've added some features with demos i had at hand

2021-03-11 23:12 UTC, alanz requested changes
LG, minor nit.

2021-03-11 23:12 UTC, alanz commented on README.md
>    until GHC 8.12 which [will report warnings](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2377)
8.12 became 9.0

2021-03-11 23:30 UTC, alanz approved these changes

2021-03-12 06:30 UTC, jneira commented on README.md
> +    '$everything': -haddock
```suggestion
    "$everything": -haddock
```

2021-03-13 20:37 UTC, merged